# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: <%= configatron.database.development.adapter %>
  encoding: <%= configatron.database.development.encoding %>
  pool: <%= configatron.database.development.pool %>
  timeout: <%= configatron.database.development.timeout %>
  socket: <%= configatron.database.development.socket %>
 
development:
  <<: *default
  host: <%= ENV['DB_HOST'] || configatron.database.development.host %>
  port: <%= configatron.database.development.port %>
  username: <%= configatron.database.development.username %>
  password: <%= configatron.database.development.password %>
  database: <%= configatron.database.development.database %>

test:
  <<: *default
  adapter: <%= configatron.database.test.adapter %>
  host: <%= configatron.database.test.host %>
  port: <%= configatron.database.test.port %>
  socket: <%= configatron.database.test.socket %>
  username: <%= configatron.database.test.username %>
  password: <%= configatron.database.test.password %>
  database: <%= configatron.database.test.database %>
  encoding: <%= configatron.database.test.encoding %>
  pool: <%= configatron.database.test.pool %> 

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3
